name       : perl-authen-sasl
version    : 2.16
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/Authen-SASL-2.16.tar.gz : 6614fa7518f094f853741b63c73f3627168c5d3aca89b1d02b1016dc32854e09
license    : GPL-2.0-or-later
summary    : Authen::SASL - SASL Authentication framework
component  : programming.perl
description: |
    Authen::SASL - SASL Authentication framework
setup      : |
    export PERL_USE_UNSAFE_INC=1
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
