name       : perl-authen-sasl
version    : 2.16
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/Authen-SASL-2.16.tar.gz : 6614fa7518f094f853741b63c73f3627168c5d3aca89b1d02b1016dc32854e09
license    : GPL-2.0
summary    : Authen::SASL - SASL Authentication framework
description: |
    Authen::SASL - SASL Authentication framework
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
    rm -rf %installroot%/usr/lib/perl5/5.20.1/
